name: upload html file

on:
  push:
    branches:
      - main

jobs:
  upload_file:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'checkout'
        uses: 'actions/checkout@master'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.3.1'
        with:
          create_credentials_file: 'true'
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - id: 'gcloud'
        name: 'upload html file'
        # https://github.com/google-github-actions/auth/issues/28
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud alpha storage cp upload_code/after/*.html gs://example-github-actions-oidc-gcp
